services:
  db-node-app:
    image: db-node-app:latest
    ports:
      - "6969:6969"
    networks:
      - db-node-network
    environment:
      REDIS_URL: redis://localhost:6379
      RUST_LOG: info
      MASTER_URL: http://master-app:3000
      LOG_SERVER_URL: http://log-app:8000/log/
      DELAY: 200
    deploy:
      replicas: 3
    depends_on:
      - master-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6969/swarm-check"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 6s

  master-app:
    image: master-node-app:latest
    environment:
      INTERVAL: 5
    ports:
      - "3000:3000"
    networks:
      - db-node-network

  log-app:
    image: log-server-app:latest
    ports:
      - "8000:8000"
    networks:
      - db-node-network

  visualization-app:
    image: visualization-app:latest
    ports: 
      - "8080:8080"
    networks:
      - db-node-network
    volumes:
      - ./visualization/plot.js:/app/plot.js:ro
      - ./visualization/index.html:/app/index.html:ro

networks:
  db-node-network:
    external: true
